// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
var aws_app_analytics = 'enable';
var aws_cognito_identity_pool_id = 'eu-west-1:74e758a9-2101-4b57-85dd-8024036388d8';
var aws_cognito_region = 'eu-west-1';
var aws_mobile_analytics_app_id = '96a49babbc234afca450ae1798355f45';
var aws_mobile_analytics_app_region = 'us-east-1';
var aws_project_id = 'eb278510-dafb-4737-b4f3-16ec567f1ea3';
var aws_project_name = 'cloud-react-native';
var aws_project_region = 'eu-west-1';
var aws_resource_name_prefix = 'cloudreactnative-mobilehub-875735674';

AWS.config.region = aws_project_region;
AWS.config.credentials = new AWS.CognitoIdentityCredentials({
    IdentityPoolId: aws_cognito_identity_pool_id
  }, {
    region: aws_cognito_region
  });
AWS.config.update({customUserAgent: 'MobileHub v0.1'});
